fix: endpoints in dev server should never have trailing slash
withastro/astro pull request #10216
Opened 2024-02-23 14:10 UTC by ematipico

## Changes

Closes https://github.com/withastro/astro/issues/10149

## Testing

Added a new test case. It seems we didn't have one.

## Docs

2024-02-23 14:13 UTC, lilnasy commented on .changeset/dry-suns-protect.md
> +Fixes a regression where the dev server was returning a 404 when hitting an endpoint, when the app was configured with `trailingSlash: "never"`
Did you mean "always"?

2024-02-23 14:14 UTC, ematipico commented on .changeset/dry-suns-protect.md
> +Fixes a regression where the dev server was returning a 404 when hitting an endpoint, when the app was configured with `trailingSlash: "never"`
I did!

2024-02-23 14:17 UTC, matthewp approved these changes

2024-02-23 14:17 UTC, lilnasy requested changes
Assuming the changeset needs to be corrected, I think this is the wrong call.

Users should configure "trailingSlash" to inform the dev server that the production server will behave a certain way so it should too. If the behavior doesn't match, they may need to configure something else. `trailingSlash` is doing what the config is telling it to.

2024-02-23 14:19 UTC, matthewp commented
Hm, that's a good point, let's chat about it.

2024-02-23 14:20 UTC, lilnasy commented
Test cases already exist in [test/units/routing/trailing-slash.test.js](https://github.com/withastro/astro/pull/9597/files#diff-859cc2635b0ceffafe57a59e8c20d9c4fb5b5cb70b9245c430e5335b1b2b46ee)

2024-02-23 14:28 UTC, closed without merging

2024-03-02 21:14 UTC, kripod commented
I‘m afraid this issue still persists: https://github.com/withastro/astro/issues/10149#issuecomment-1961767578

[Static File Endpoints](https://docs.astro.build/en/guides/endpoints/#static-file-endpoints) exposing e.g. `.png` assets for dynamic social image generation can‘t be accessed as `/img.png` in dev mode, as only `/img.png/` would pass the overly strict trailing slash requirements.