deprecation(vercel): vercel-edge-middleware.js file
withastro/astro pull request #10476
Opened 2024-03-18 16:33 UTC by lilnasy

## Changes

- The `vercel-edge-middleware.js` file allowed users to access the [vercel edge runtime's `RequestContext`](https://vercel.com/docs/functions/edge-middleware/middleware-api#requestcontext) object, and create the middleware `locals` from its fields. However, this object [includes only one field](https://github.com/vercel/vercel/blob/vercel@33.6.1/packages/edge/src/request.ts#L13) - the `waitUntil()` function - which is now available directly as `ctx.locals.waitUntil()`.
- [Edge Middleware API Reference](https://vercel.com/docs/functions/edge-middleware/middleware-api#requestcontext)
- [@vercel/edge types](https://github.com/vercel/vercel/blob/vercel@33.6.1/packages/edge/src/request.ts#L13)

<details>
<summary>

- `console.log(context)`

</summary>

![image](https://github.com/withastro/astro/assets/69170106/46de5315-f3f0-46af-8ead-fd819509f981)

</details>

## Testing
- Edge runtime behavior. Manually tested.

## Docs
- https://github.com/withastro/docs/pull/7466
- https://github.com/withastro/docs/pull/7485

2024-03-18 22:46 UTC, ematipico requested changes
A couple of things. The first one (the important one) is that we **must** expose the types to the users to **augment** the `Astro.locals` types.

The second one (less important), is that Netlify and Cloudflare adapters have using their named object e.g. `Astro.locals.netlify`. It would be nice if we could align it, but it's nice to have.

2024-03-19 14:18 UTC, lilnasy commented
@ematipico addressed

2024-03-19 14:22 UTC, ematipico approved these changes
Thank you! I left a comment (now outdated) in the docs PR too.

2024-03-19 14:52 UTC, lilnasy commented
@ematipico Added docs for typing here: https://github.com/withastro/docs/pull/7485

2024-03-20 14:33 UTC, merged