Update sharp to 0.33 to fix issue with Alpine Linux
withastro/astro pull request #10684
Opened 2024-04-04 20:56 UTC by PeterDraex

## Changes

It was impossible for me to use the Astro image service in an Alpine Linux docker container. Even though I would install sharp `0.33.3` in my app, pnpm would download version `0.32.6`, which doesn't work in Alpine Linux container. I have to override the downloaded version in my package.json. 

For more details about the issue see:
- https://discord.com/channels/830184174198718474/1224861729792458803/1224861729792458803
- https://github.com/lovell/sharp/issues/4054

This PR updates the version of the `sharp` dependency to `^0.33` and thus makes Astro compatible with Alpine Linux containers.

TODO
- [] Don't forget a changeset! `pnpm exec changeset`

## Testing

## Docs

2024-04-04 22:42 UTC, Princesseuh requested changes
Blocking this because it's a breaking change. Sharp's 0.33.0 `engines` contract is stricter than Astro's, requiring a higher version of Node 18 and 20 than Astro, and not supporting Node 19 at all. 

As such, for a certain percentage of users, Sharp would just not get installed ever unless they forced the install. Last time we updated to 0.33.0 (because I didn't know its checks were stricter than us, ha), we ended up with a bunch of support threads from people running outdated versions of Node.

2024-04-19 08:05 UTC, Princesseuh commented on packages/astro/package.json
> +    "sharp": "^0.33"
```suggestion
    "sharp": "^0.33.3"
```

2024-04-19 08:06 UTC, Princesseuh approved these changes
Thank you, this looks great!

2024-04-19 08:07 UTC, Princesseuh commented on pnpm-lock.yaml
> +        specifier: ^0.33
```suggestion
        specifier: ^0.33.3
```

2024-04-19 09:44 UTC, ematipico approved these changes

2024-04-22 17:36 UTC, sarah11918 reviewed
Thanks for this helpful contribution @PeterDraex !  I've just updated the changeset message to be a tiny bit more explicit. Especially since this is being released with a minor version of Astro, we try to give the changesets a little extra love and attention as people are checking more closely!  :raised_hands:

2024-04-22 17:36 UTC, sarah11918 commented on .changeset/famous-mugs-grab.md
> +Update sharp to 0.33 to fix issue with Alpine Linux
```suggestion
Updates sharp to version 0.33 to fix issues when using an Alpine Linux container.
```

2024-04-23 17:17 UTC, PeterDraex commented
> @PeterDraex would you mind rebasing with `main` and rerunning install to update the lockfile?

@matthewp Done. I've also updated sharp version in `examples/starlog/package.json`. Is that okay?

2024-04-24 14:20 UTC, merged