fix(cli): hardcoded supported Node.js version
withastro/astro pull request #10742
Opened 2024-04-10 14:13 UTC by ematipico

## Changes

Follow up of the PR that updated the defined engines inside our `package.json` files

## Testing

N/A

## Docs

N/A

2024-04-10 14:15 UTC, bluwy approved these changes

2024-04-10 14:22 UTC, Princesseuh requested changes
Only do this for Astro 5! This is super breaking otherwise.

2024-04-10 14:29 UTC, ematipico commented
Ooops, sorry 😆 I misunderstood that

2024-08-06 09:22 UTC, Princesseuh approved these changes

2024-08-06 09:23 UTC, merged