feat: prefer using x-forwarded-for as clientAddress
withastro/astro pull request #11101
Opened 2024-05-20 07:46 UTC by linguofeng

## Changes

Added logic to extract the client's IP address from the request headers (x-forwarded-for)

## Testing

CI should pass

## Docs

N/A

2024-05-20 14:14 UTC, matthewp approved these changes

2024-05-21 09:00 UTC, ematipico requested changes

2024-05-21 09:00 UTC, ematipico commented on .changeset/healthy-planets-dream.md
> +prefer using x-forwarded-for as clientAddress
```suggestion
The adapter now uses **first** the header `x-forwarded-for` for computing `clientAddress`.
```

2024-05-21 09:59 UTC, ematipico approved these changes

2024-05-21 10:27 UTC, florian-lefebvre approved these changes

2024-05-22 07:32 UTC, ematipico commented on .changeset/healthy-planets-dream.md
> +The adapter now uses **first** the header `x-forwarded-for` for computing `clientAddress`.
```suggestion
Updates Astro's code for adapters to use the header `x-forwarded-for` to initialize the `clientAddress`.

To take advantage of the new change, integration authors must upgrade the version of Astro in their adapter `peerDependencies` to `4.9.0`.
```

2024-05-22 11:10 UTC, merged