feat: add first and last to the Page interface
withastro/astro pull request #11176
Opened 2024-06-02 07:23 UTC by tsawada

## Changes

Add `page.url.first`, `page.url.last` to the Page interface.
Closes https://github.com/withastro/roadmap/discussions/862

## Testing
I couldn't find relevant tests for `page.url`. Let me know if there is one already.

## Docs
This needs to be updated
https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/routing.mdx#complete-api-reference

/cc @withastro/maintainers-docs for feedback!

2024-06-04 02:14 UTC, bluwy commented on .changeset/twenty-maps-glow.md
> +'astro': major
```suggestion
'astro': minor
```
It's a minor as it introduces a feature but doesn't break anything.

2024-06-04 02:14 UTC, bluwy approved these changes

2024-06-21 06:56 UTC, bluwy commented
Looks like we forgot to followup on this PR. I queued this up for the next minor in 4.12.0

2024-06-27 14:41 UTC, sarah11918 requested changes
Just placeholding for docs here! When I get a docs PR, then I'll be able to review!

2024-06-27 14:41 UTC, sarah11918 commented on .changeset/twenty-maps-glow.md
> +feat: Add urls to the first and the last page in the Page interface
This will need updating, will wait to see what the docs PR is to know what to suggest.

2024-07-03 14:43 UTC, matthewp commented
Will need docs for this. @tsawada will you be able to write them?

2024-07-08 11:29 UTC, sarah11918 commented
Added a docs PR with my suggestion here, since this appears to be similar to other existing items. Please read carefully for accuracy, as I inferred e.g. when the value is undefined based on the previous and next entries!

https://github.com/withastro/docs/pull/8751

2024-07-08 11:41 UTC, sarah11918 reviewed
Thank you for this very handy addition to the `page` prop, @tsawada ! I think people will make very good use of this!  :raised_hands: 

I've gone ahead and drafted a Docs PR to accompany this, but I will need you to review and make sure it's accurate, as well as my suggestion here for the message that will show up in the CHANGELOG.

So, docs aren't ready to go but I've tried to move them along with a suggestion. Once you've approved or corrected them, then Docs is happy!

2024-07-08 11:41 UTC, sarah11918 commented on .changeset/twenty-maps-glow.md
> +feat: Add urls to the first and the last page in the Page interface
```suggestion
Adds two new values to the [pagination `page` prop](https://docs.astro.build/en/reference/api-reference/#the-pagination-page-prop): `page.first` and `page.last` for accessing the URLs of the first and last pages.
```
Maybe something like this? When new options are added, I do always think it's helpful if the changeset message mentions them by name!

2024-07-12 11:02 UTC, sarah11918 approved these changes
Approving for docs!

2024-07-17 14:55 UTC, merged