fix: Add html extension if build.format is file
withastro/astro pull request #11684
Opened 2024-08-12 19:25 UTC by fjdelarubia

## Changes

This change adds .html extension to the sitemap urls if the build.format is set to **file**, this way the urls will match with the canonical url

Sample project's structure:

<img width="244" alt="image" src="https://github.com/user-attachments/assets/d3ccffa4-f7ef-4eaf-baaa-a3aac2ff5ce1">

Before urls:
https://some-site.com/legal/aviso-legal
https://some-site.com/legal/cookies
https://some-site.com/legal/politica-de-privacidad
https://some-site.com/legal/terminos-y-condiciones
https://some-site.com/legal
https://some-site.com/productos/carteles-personalizados/carteles-para-bodas
https://some-site.com/productos/carteles-personalizados/carteles-para-cumplea%C3%B1os
https://some-site.com/productos/natalicios
https://some-site.com/

After urls:
https://some-site.com/legal/aviso-legal.html
https://some-site.com/legal/cookies.html
https://some-site.com/legal/politica-de-privacidad.html
https://some-site.com/legal/terminos-y-condiciones.html
https://some-site.com/legal.html
https://some-site.com/productos/carteles-personalizados/carteles-para-bodas.html
https://some-site.com/productos/carteles-personalizados/carteles-para-cumplea%C3%B1os.html
https://some-site.com/productos/natalicios.html
https://some-site.com/

## Testing

I need some help for the test, would be ok to create new fixture for static build with new build format?

## Docs

This PR tries to fix the sitemap behaviour to match the [canonical url explained in the docs](https://docs.astro.build/en/reference/api-reference/#astrourl), see #11575

2024-08-26 11:33 UTC, ematipico requested changes
I am not sure this is the correct fix. You should not add `.html` to the final URLs.

2024-08-30 13:05 UTC, matthewp commented
Thanks! The `build.format` option is only for the build, to tell it how to output files. It doesn't signal what URLs are supposed to look like. That's determined by your server. If you want to have `.html` in your URLs maybe adding an option in the sitemap integration is a better way to go.

2024-08-31 15:38 UTC, fjdelarubia commented
> Thanks! The `build.format` option is only for the build, to tell it how to output files. It doesn't signal what URLs are supposed to look like. That's determined by your server. If you want to have `.html` in your URLs maybe adding an option in the sitemap integration is a better way to go.

I think not only in the sitemap integration, but on the build process the .html extension is added here https://github.com/withastro/astro/blob/main/packages/astro/src/core/build/generate.ts#L375

This url is used for creating the request which renders the page, and it adds the .html extension to the pathname, which makes the canonical url to contain the .html extension.

The .html extension were added here:
https://github.com/withastro/astro/commit/cd154e447ba7883531d484deea2fd046898d749b

If the .html extension should not be visible, nor in the canonical url nor the sitemap, just removing it from the default state would fix it

```
switch (format) {
		case 'directory':
		case 'preserve': {
			ending = trailingSlash === 'never' ? '' : '/';
			break;
		}
		default: {
			ending = '';
			break;
		}
	}
``

2025-01-13 10:41 UTC, ematipico commented
> which makes the canonical url to contain the .html extension.

How does this affect the final output, though? I see your point, and if this affects the output in anyway, we can't have this PR as a fix because it will break a lot of websites

2025-02-04 14:48 UTC, fjdelarubia commented
> > which makes the canonical url to contain the .html extension.
> 
> How does this affect the final output, though? I see your point, and if this affects the output in anyway, we can't have this PR as a fix because it will break a lot of websites

Yep, I don't know what would be the fix, I'm just closing this PR

2025-02-04 14:48 UTC, closed without merging