Fix reference in create-astro
withastro/astro pull request #12085
Opened 2024-09-27 10:26 UTC by TheOtterlord

## Changes

Fix the version message when running create-astro with a reference.

## Testing

Manually

## Docs

N/A

2024-09-30 03:15 UTC, bluwy approved these changes

2024-10-01 11:31 UTC, Princesseuh commented on packages/create-astro/src/messages.ts
> +		const { version } = await fetch(`${registry}/${packageName}/${ref}`, {
as we've discovered during the offsite, this ends up not working. In one time ref refers to a branch, in the other it refers to a npm tag. For instance, `astro@next` does not exist, so setting `--ref next` would not work.

2024-10-01 11:32 UTC, Princesseuh requested changes
See comment, this does not work because ref and branches tags don't match

2024-10-10 16:06 UTC, TheOtterlord commented
Yeah, this can close. This relied on publishing `@next` or hosting a `beta` branch

2024-10-10 16:06 UTC, closed without merging