Added generateId option for file loader
withastro/astro pull request #12308
Opened 2024-10-25 23:38 UTC by marceloverdijk

Background: https://github.com/withastro/roadmap/discussions/1045

## Changes

- Adds a generateId option to the file loader (similar as the glob loader already has)
- Don't forget a changeset! `pnpm exec changeset`

## Testing

## Docs

/cc @withastro/maintainers-docs for feedback!

2024-11-02 14:50 UTC, ascorbic commented
This is great. Thanks! Could you add a changeset that can form the basis for updated docs?

2024-11-02 15:16 UTC, marceloverdijk commented
Sure will do it later today 👍

2024-11-02 16:29 UTC, marceloverdijk commented
@ascorbic I've added the changeset, is this sufficient?

2024-11-04 13:39 UTC, ematipico requested changes
Thank you @marceloverdijk for the contribution! 

There are three things I ask you to implement:
- Change the changeset to be `patch`. Content Layer is experimental, so we can land new APIs under `patch`.
- Create at least a new test to verify that your implementation works. Let me know if you need any help with that. You can start from here https://github.com/withastro/astro/blob/76803498738f9e86e7948ce81e01e63607e03549/packages/astro/test/content-layer.test.js#L56
- Docs. For now our docs are here: https://github.com/withastro/astro/blob/76803498738f9e86e7948ce81e01e63607e03549/packages/astro/src/%40types/astro.ts#L2213-L2242 . You'll have to provide a new example with the new API

2024-11-12 16:21 UTC, sarah11918 commented
Let me know if I can be of any help with docs here! :raised_hands:

2025-01-09 16:06 UTC, florian-lefebvre commented
Hi! are you still interested in this PR? I'll note docs now live in the docs repo, the changeset should likely remain minor now but a test will still be needed

2025-01-31 13:50 UTC, florian-lefebvre commented
Closing for inactivity, feel free to reopen if you're interested in brining it back to life

2025-01-31 13:50 UTC, closed without merging