fix(i18n): pass search params to fallback
withastro/astro pull request #12547
Opened 2024-11-28 00:12 UTC by mtwilliams-code

## Changes

- makes the i18n middleware when used for fallbacks pass on the search params to the subsequent render.
- closes issue #12546 

## Testing

Tested locally with the same code in the stackblitz example in issue. Ran all i18n test suites. Did not add a specific test for this - if maintainers want I will, but wanted feedback on willingness to include this before I dove into the fixtures.

## Docs

/cc @withastro/maintainers-docs for feedback!
May need docs. The current behavior is also undocumented and imo less intuitive.

2024-11-29 16:36 UTC, ascorbic commented
This looks good. Could you add a test for this? Probably in `packages/astro/test/i18n-routing.test.js`

2024-12-02 18:55 UTC, mtwilliams-code commented
@ematipico this seems to be your baby - any concerns?

2024-12-04 10:23 UTC, ematipico requested changes
The fixes look good, we need to address the changeset, it's not a minor (this is a blocker)

I also, I suggested few changes in the tests.

2024-12-04 10:23 UTC, ematipico commented on .changeset/kind-mayflies-argue.md
> +pass search params to i18n fallbacks
```suggestion
Fixes a bug where URL search parameters weren't passed when using the i18n `fallback` feature.
```

2024-12-04 10:23 UTC, ematipico commented on packages/astro/test/i18n-routing.test.js
> +			assert.equal(text.includes('search=1'), true);
```suggestion
			assert.match(text, /Oi essa e start/);
			assert.match(text, /search=1/);
```

2024-12-04 10:23 UTC, ematipico commented on .changeset/kind-mayflies-argue.md
> +'astro': minor
```suggestion
'astro': patch
```

2024-12-05 06:22 UTC, ematipico approved these changes

2024-12-05 06:23 UTC, merged