fix: do not freeze process.env in dev
withastro/astro pull request #12585
Opened 2024-12-02 15:51 UTC by florian-lefebvre

## Changes

- In dev, use `globalThis`

## Testing

- [ ] Tests should still pass
- [ ] Test manually
- [ ] Test on a private project 

## Docs

N/A

2024-12-02 15:52 UTC, florian-lefebvre commented on packages/astro/src/env/vite-plugin-env.ts
> +				(globalThis as any)[ENV_SYMBOL] = loadedEnv;
That's the actual fix

2024-12-04 15:39 UTC, florian-lefebvre commented
/snapshot astroenv-dev

2024-12-04 16:31 UTC, ematipico approved these changes
Looks good! I left a nit around the template

2024-12-04 16:31 UTC, ematipico commented on packages/astro/templates/env.mjs
> +	return _getEnv(key);
This code will end up with two `return` statements, which isn't the best. Maybe we can leave the placeholder and add an `else` clause to the `if` we have `vite-plugin-env.ts`, line 157, which will replace the placeholder with `return _getEnv(key)`

2024-12-04 17:00 UTC, bluwy requested changes
Blocking until we have a solution for https://github.com/withastro/astro/issues/12618

2024-12-06 15:56 UTC, florian-lefebvre commented
@bluwy I think I have a fix for that issue, see [`4da93c6` (#12585)](https://github.com/withastro/astro/pull/12585/commits/4da93c62f1a17806e4faffbbae1bbc9bd5e62738)

2024-12-06 16:03 UTC, ematipico approved these changes
The code looks good. I can help you to test it with a preview release

2024-12-06 16:03 UTC, ematipico commented on packages/astro/templates/env.mjs
> +// @ts-ignore
```suggestion
// @ts-expect-error
```

2024-12-06 16:04 UTC, florian-lefebvre commented
/snapshot astroenv-dev

2024-12-06 21:37 UTC, bluwy commented
With the latest fix, I think it would fix the regression for now. But it doesn't fix the case where `.env` file updates are handled I think. If so, I'm still fine with merging this as a stop gap though.

2024-12-07 08:24 UTC, florian-lefebvre commented
I'll test it on monday

2024-12-09 07:45 UTC, florian-lefebvre commented
@bluwy I just tested manually in the basics example woth `import.meta.env`, `process.env` and `astro:env/server` and dev reloading works fine

2024-12-09 12:29 UTC, merged