feat: setup branch
withastro/astro pull request #12777
Opened 2024-12-18 14:58 UTC by florian-lefebvre

## Changes

- What does this change?
- Be short and concise. Bullet points can help!
- Before/after screenshots can help as well.
- Don't forget a changeset! `pnpm exec changeset`

## Testing

## Docs

2025-01-17 14:01 UTC, florian-lefebvre commented
[TS Playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAMg9gYwIYBsBicB2w1ILYCWKIUAvFAN4BQUtUYATnAG4EAmEDAXFAEQqJUvADQ06AZwYIewBgFcIVAL5VVoSFADKwJJjZIGbDNlyFiAHgAqABSasODKBAAewCHvFRxsgpgDmAHxkUDZ27JxOru5snvyCKLxQAPxQmBDMETzUdPRhDjyhLOEMyqq+bgwAZkgI0ADCWJUEflYAcvjQLm4eXj7+wWkZDMIhxjj4RAQQnl3RngCCDAxIIObwyOhY42YkAD5aOnoGRlumRKuW7XjQ+7x+cHB+KBC8AUHkg5xB2XSMRQ7iJI8ADalw6AF1It0YlBgZ8GJCUotlqsKKkOjxvAxfH4oEogjxkStzGjMBiQldoPixLRqmYpuIQWDrpDZj04elOIioETVutUGMzsQoPttLp9IZBRMLHcHk8XiKoAAKLE4qAAMkoSgAlG8oAUpfTpqUqAB6U1QBBYbxQZw8BqYJotXiVB6JfYAcgARgYPe9KGaLTk-vZOIzYaTyS63XjwaJzTkoHTJtMQWiQ8UeLwfQwRLHA3jVFbMDa7VAHU7gj9aBmAWn0dcs664IklHGaUnpQz67XOFn7o9nq2Rum8n2+Dnh5Rcv9x3ENnnJNIoLIFPmVFRizaOE00hXmsFzB3mZ0oj1Vf0PpzhsfDSmZmeYby1vE78LRYcJScTNKLpTFbKg4vHqV5DFQARKsWTr2o0zRtB0IyWG+DIBNqZBBFBzRFtawBQCQ5A7r4ED7n4SrVjOoYMOGwKRo2fDNlOtEQFmk6xqIOTJig3YRhRmZ8AO8qMbx+R8AIC4jEuMjyFSI7CXOrFKLJvbcHwzituCyjakAA)

2025-01-20 16:01 UTC, ascorbic approved these changes
Looks good so far

2025-01-21 11:15 UTC, ematipico requested changes

2025-01-21 11:15 UTC, ematipico commented on packages/astro/src/config/index.ts
These types **must** be exported from `types/public/config.js` 

As part of Astro v5, we did a big refactor and moved all types inside `types/public` and `type/private`, so we know whether some types are public (for users to use) or not

2025-01-21 11:15 UTC, ematipico commented on packages/astro/src/core/config/schema.ts
> +								message: `Invalid provider "${family.provider}"`,
We could do better and list the valid providers since we already have them in `providersNames`.

2025-01-21 11:15 UTC, ematipico commented on packages/astro/src/assets/fonts/types.ts
> +	entrypoint: string;
`entrypoint` should be a string or a `URL`. Since v5, all entry points now accept `URL` too

2025-01-21 11:15 UTC, ematipico commented on packages/astro/src/assets/fonts/providers/adobe.ts
> +		entrypoint: 'astro/assets/fonts/providers/adobe',
Entrypoints should have the file extension. E.g. `astro/assets/fonts/providers/adobe.js`

2025-01-21 11:15 UTC, ematipico commented on packages/astro/src/assets/fonts/providers/google.ts
> +		entrypoint: 'astro/assets/fonts/providers/google',
I think the paths of built-in providers are wrong. They should be `dist/assets/fonts/providers/..`

2025-01-21 11:29 UTC, ascorbic commented on packages/astro/src/assets/fonts/providers/google.ts
> +		entrypoint: 'astro/assets/fonts/providers/google',
Presumably they will be resolved as imports, and `astro/assets/fonts/*` could be added to exports

2025-01-21 14:11 UTC, florian-lefebvre commented on packages/astro/src/assets/fonts/providers/google.ts
> +		entrypoint: 'astro/assets/fonts/providers/google',
The entrypoint is used as a placeholder for now, to try figure out the API. I'll address it in the following PR

2025-01-21 14:11 UTC, florian-lefebvre commented on packages/astro/src/assets/fonts/types.ts
> +	entrypoint: string;
I'll address this in the next PR

2025-01-21 14:14 UTC, florian-lefebvre commented on packages/astro/src/config/index.ts
I think these types should remain private, because we have a `defineFontProvider` type utility. What do you think?

2025-01-21 15:01 UTC, ematipico commented on packages/astro/src/config/index.ts
> What do you think?

It's very difficult to predict how users will use our APIs, but users can definitely do something like:

```js

function highOrderDefineProvider() {
	return something;
}

export function defineProvider() {
	return highOrderDefineProvider()
}
```

Plus, if a user uses `--isolatedModules` from typescript, they are forced by the compiler to have types everywhere, even then they can be inferred by the compiler, which means that that uses are forced to have type, which we should provide.

2025-01-21 15:02 UTC, ematipico approved these changes

2025-01-21 15:09 UTC, merged