Adds ‹div›RIOTS logo to the list of sponsors
withastro/astro pull request #2271
Opened 2021-12-24 15:12 UTC by georges-gomes

## Changes

- Adds 2 images in assets where the other sponsors are.
- Adds dark/light images in Sponsors section.

## Testing

Tested on my fork - README.md
dark/light mode

## Docs

No doc required

Thanks and Merry Christmas 🎁

2021-12-24 16:36 UTC, Chrissdroid requested changes

2021-12-24 16:36 UTC, Chrissdroid commented on packages/astro/README.md
> +
As it's a gold sponsor, i think you can add a new section here
```suggestion
### Gold Sponsors

<table>
  <tbody>
    <tr>
      <td align="center">
        <a href="https://divRIOTS.com#gh-light-mode-only" target="_blank">
        <img width="150" height="40" src="https://raw.githubusercontent.com/withastro/astro/main/.github/assets/divriots.svg#gh-light-mode-only" alt="‹div›RIOTS" />
        </a>
        <a href="https://divRIOTS.com#gh-dark-mode-only" target="_blank">
        <img width="150" height="40" src="https://raw.githubusercontent.com/withastro/astro/main/.github/assets/divriots-dark.svg#gh-dark-mode-only" alt="‹div›RIOTS" />
        </a>
      </td>
    </tr>
  </tbody>
</table>

### Sponsors

```

2021-12-24 23:59 UTC, georges-gomes commented
Thanks @Chrissdroid 🙏

2021-12-28 00:24 UTC, matthewp commented
Looks great, thanks!

2022-01-04 18:37 UTC, natemoo-re approved these changes

2022-01-04 18:38 UTC, merged