build-css resolve should return false instead of undefined
withastro/astro pull request #2347
Opened 2022-01-08 19:58 UTC by hans-d

## Changes

Resolve function of vite plugin build-css should return false instead of undefined in case an id can not be resolved.

This allows for some vite plugins to function on astro build. Working eg windicss. 
Not working: unocss (caused by how unocss is setup)

## Testing

Run regular ci tests

Manually verified using windicss and unocss plugins.
Unclear yet how to add proper test

## Docs

No feature change.

2022-01-10 18:09 UTC, natemoo-re commented
This looks good to me, going to rerun our CI to see if that was a flaky failure or if something else is going on.

2022-01-10 22:11 UTC, jonathantneal commented
Could we add tests for this?

> Returning `null` defers to other `resolveId` functions and eventually the default resolution behavior. Returning `false` signals that source should be treated as an external module and not included in the bundle.
> — https://rollupjs.org/guide/en/#resolveid

I am concerned this could negatively affect many other plugins, as it always returns something that would end resolution.

I think `false` should only be returned when we _know_ something is an external module, rather than because it was not something we knew.

2022-01-10 22:11 UTC, jonathantneal requested changes
Could we add tests for this?

> Returning `null` defers to other `resolveId` functions and eventually the default resolution behavior. Returning `false` signals that source should be treated as an external module and not included in the bundle.
> — https://rollupjs.org/guide/en/#resolveid

I am concerned this could negatively affect many other plugins, as it always returns something that would end resolution.

I think `false` should only be returned when we _know_ something is an external module, rather than because it was not something we knew.

2022-01-11 03:45 UTC, hans-d commented
In case of windicss, the original import is `import 'virtual:windi.css'`

`resolveId` gets the following:
- `id`: `/@windicss/windi.css`
- `importer`: `@astro-page-all-styles/index.js`
- `options`: `{ custom: {}, isEntry: false }` (and second time `{ custom: { 'node-resolve': { isRequire: false } }, isEntry: false }`)

Where  windicss adjusts the id in  https://github.com/windicss/vite-plugin-windicss/blob/main/packages/shared/virtual-module.ts#L17-L24

I've tried various forms of 

```
  vite: {
    build: {
      rollupOptions: {
        external: ['/@windicss/windi.css', 'virtual:windi.css'],
      },
    },
  },
```

As no options are provided, the only thing I can think of now is to do a check on the /@windicss prefix, which feels kind of ugh.

2022-01-12 19:11 UTC, hans-d commented
Some research notes. 

Besides return false, also returning the id `/@windicss/windi.css` will make it work.

I've modified vite-plugin-windicss so that `virtual:windi.css` gets resolved to `'\0' + '/@windicss/windi.css'`, and upped the log levels a bit.

i see that windicss load(id) is processing it's file, eg id `__x00__/@windicss/windi.css` is processed.

@astrojs/rollup-plugin-build-css is getting in resolveId: (3 params)
```
/@id/__x00__/@windicss/windi.css @astro-page-all-styles/index.js { custom: {}, isEntry: false } undefined
/@id/__x00__/@windicss/windi.css @astro-page-all-styles/index.js { custom: { 'node-resolve': { isRequire: false } }, isEntry: false } undefined
```
followed by
```
[vite]: Rollup failed to resolve import "/@id/__x00__/@windicss/windi.css" from "@astro-page-all-styles/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "/@id/__x00__/@windicss/windi.css" from "@astro-page-all-styles/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external
```

From https://vitejs.dev/guide/api-plugin.html#conventions (_emphasis_ mine)

> Internally, plugins that use virtual modules should prefix the module ID with \0 while resolving the id, a convention from the rollup ecosystem. This prevents other plugins from trying to process the id (like node resolution), and core features like sourcemaps can use this info to differentiate between virtual modules and regular files. \0 is not a permitted char in import URLs so we have to replace them during import analysis. _A \0{id} virtual id ends up encoded as /@id/__x00__{id} during dev in the browser._ The id will be decoded back before entering the plugins pipeline, so this is not seen by plugins hooks code.

2022-01-17 11:16 UTC, hans-d commented
windicss is now picked up nicely with using --experimental-static-build. closing this one

2022-01-17 11:16 UTC, closed without merging