Move SASS to devDependencies
withastro/astro pull request #2572
Opened 2022-02-11 20:28 UTC by Princesseuh

## Changes

Move SASS to be a devDependency instead of a normal dependency. The reason for this change is that we shouldn't be shipping SASS ourselves, not only does both the Astro and the Vite documentation says to manually add it to your project but I also think that it's useless to be shipping it ourselves when in reality, probably only a minority of our users uses it (this makes Astro about 5mb smaller for most people!)

For context, here's what the current docs says about it:

> Sass: Run npm install -D sass and use <style lang="scss"> or <style lang="sass"> (indented) in .astro files
Stylus: Run npm install -D stylus and use <style lang="styl"> or <style lang="stylus"> in .astro files
Less: Run npm install -D less and use <style lang="less"> in .astro files.

Users who don't have it installed will simply get an error saying to install SASS, so users experiencing issues due to this will easily be able to migrate to the new setup needed to get SASS working

It's still needed as a DevDependency however as we have a test that uses it

## Testing

Ran tests and everything worked, including the SASS test

## Docs

No docs needed as the current docs are accurate on this

2022-02-11 21:11 UTC, jonathantneal approved these changes

2022-02-11 21:11 UTC, jonathantneal commented
Good catch. I agree. It looks like failing test has nothing to do with this change, but I’m going to let other eyes look it over.

2022-02-11 21:25 UTC, matthewp commented
Do we have consensus on this? I think making sass not included by default but I don't recall us landing on changing that yet. I believe this needs an RFC.

2022-02-11 21:28 UTC, matthewp requested changes
Flagging this for discussion with the core team (or on the RFC call). I'm not against this change myself, I'm just unsure if we've reached consensus on this yet or not.

Let's keep this open until it's discussed, however.

2022-02-14 23:51 UTC, FredKSchott commented
+1 from me, I just saw the same thing over the weekend and meant to bring it up. @Princesseuh thanks for surfacing this!

Our docs tell you to `npm install sass` so this feels like a remnant from the before times. However, that doesn't meant that this won't be a breaking change for people who skipped that step because they could! @matthewp @natemoo-re are you aware of a check that we could run ourselves before importing/requiring sass, to give a good happy error message?

2022-02-15 19:03 UTC, matthewp approved these changes

2022-02-15 19:03 UTC, matthewp commented
I reviewed the git history and we made this change in 0.21. So approving as this was already discussed and approved.

2022-02-16 01:49 UTC, merged

2022-02-16 12:38 UTC, natemoo-re commented
> @matthewp @natemoo-re are you aware of a check that we could run ourselves before importing/requiring sass, to give a good happy error message with steps to resolve.

The Vite CSS plugin already does this for us, IIRC