Astro add docs
withastro/astro pull request #2958
Opened 2022-04-01 00:48 UTC by aFuzzyBear

Ill fill this all in, in due course, promise

## Changes

- What does this change?
- Be short and concise. Bullet points can help!
- Before/after screenshots can help as well.
- Don't forget a changeset! `pnpm exec changeset`

## Testing

## Docs

2022-04-01 14:12 UTC, natemoo-re reviewed
This is cool! Did you borrow this from somewhere? Might be nice to add a comment to link back to the source.

2022-04-01 20:53 UTC, aFuzzyBear commented
I will do, mainly it was the commands that I found but I will link it back to the source code where I got it from =)
Just going to see about tying this into the cli tool, 
Would it be out of whack to make an `astro browse <url>` ? it wouldnt be difficult at all to implement

2022-04-01 22:29 UTC, aFuzzyBear commented
Is it possible for someone to help me with getting this simple method over the line, 
I have added it as best as I could to the CLI tool, as where I believe it should go, however the issue is that the `browser()` is now not launching properly, at least when I have tried to test this on Gitpod, 

I do have some questions, 
The first is what am I doing wrong, if there is anything, please do feed this back to me, 
How/Where would I learn how to write tests for this.
If there is anything else please do let me know,

2022-04-02 00:37 UTC, aFuzzyBear commented
It now works !!!

I had miss read the cli function properly, when I realised it was a very simple fix, and it now works a peach!!

 🚀👨‍🚀📚 `astro docs` ladies and fellow astronauts is by all accounts good to go, 🚀👨‍🚀📚

2022-04-03 18:57 UTC, JuanM04 requested changes
Awesome, I love it! I've left some comments

2022-04-03 18:57 UTC, JuanM04 commented on packages/astro/src/cli/index.ts
>  	else if (flags.help) return 'help';
I'd remove that `if` and add `'docs'` to the `supportedCommands` set. That what, if anyone does `astro docs --help`, they'll see the full help message!

2022-04-04 14:55 UTC, aFuzzyBear reviewed
Applied @JuanM04 's recommendations and have moved the `cmd('docs')` to the `supportedCommands()` Also resolved the import conflicts from the main branch,

2022-04-04 15:10 UTC, aFuzzyBear commented
Kinda scared of the `changeset` it was asking if I wished to make a `major bump` of `0.25.4` and I didnt wish to regress the hard work of others, so I really have left this alone, sorry,

2022-04-06 17:19 UTC, merged