Add the `mode` option
withastro/astro pull request #4015
Opened 2022-07-21 20:07 UTC by matthewp

## Changes

- Adds the new config option `mode: 'static' | 'server'
- This opens up the ability for Adapters to add special support for static mode.
- This API is used *instead of* the presence of an adapter to enable SSR features.
- If an adapter is omitted and `mode === 'server'` we through an error during build.

## Testing

- Tests added

## Docs

TODO

2022-07-22 04:06 UTC, FredKSchott reviewed
LGTM so far!

> force people to rename adapter to deploy or stay back-compat with adapter and a deprecation notice?

I'd lean for back-compat + deprecation notice. It's cheap to do a config rename like that inside of `validateConfig()` iirc.

2022-07-22 04:06 UTC, FredKSchott commented on examples/basics/astro.config.mjs
> +  mode: "static",
remember to come back and clean this file up!

2022-07-22 13:07 UTC, matthewp commented on examples/basics/astro.config.mjs
> +import netlify from "@astrojs/netlify";
remove this

2022-07-22 13:07 UTC, matthewp commented on .changeset/lucky-apes-yell.md
> +'astro': patch
add another changeset for the mode change

2022-07-22 13:08 UTC, matthewp commented on packages/astro/src/@types/astro.ts
> +	// TODO: Document
document this config option

2022-07-22 13:08 UTC, matthewp commented on packages/astro/src/core/build/index.ts
> +				return 'node.js (generic)';
update this

2022-07-22 13:09 UTC, matthewp commented on packages/astro/src/core/build/page-data.ts
> -	const buildMode = isBuildingToSSR(astroConfig) ? 'ssr' : 'static';
I think `isBuildingToSSR` can be removed

2022-07-22 13:09 UTC, matthewp commented on packages/astro/src/core/logger/node.ts
> +	debugPackage.enable('*,-babel');
remove this

2022-07-22 13:13 UTC, matthewp commented
TODO:

- [ ] - Update adapters to throw when attempted to use with `mode: 'static'`.

2022-07-22 18:19 UTC, natemoo-re requested changes
Blocking this PR. There is an ongoing discussion on Discord about overloading the name `mode` which is a well-defined Vite-ism.

As soon as that's resolved, I'm totally on board with the core changes here.

2022-07-22 21:53 UTC, natemoo-re approved these changes

2022-07-22 21:53 UTC, natemoo-re commented on .changeset/famous-coins-destroy.md
> +New `mode` configuration option
Changeset needs to be updated to refer to `output`

2022-07-25 03:50 UTC, FredKSchott approved these changes
Thanks for helping to get this over the line @matthewp. I took a quick pass to clean this up for you so that we can merge in time for the RC. Here's a summary of the changes made on top of your PR:

- cleaned up some of the auto-doc generation types.
- cleaned up some of the old code from my original PR that had made its way into this one (old changesets, old "exports' entry, etc)
- Kept the config `output` and the term "output target"/"output mode" used to describe it.
- Reverted the `deploy` change to keep it as `adapter` for now. I'm glad that we experimented with a new name here but after trying a few out first-hand I wasn't happy with anything to the point that it would be worth the switch and increased migration cost of the more important `output` change. Let's keep it as "adapter" for now and can revisit later if user feedback is confused.

2022-07-25 04:18 UTC, merged