update example template default scripts
withastro/astro pull request #4098
Opened 2022-07-30 04:55 UTC by FredKSchott

## Changes

- Adds an `astro` script to every example for easier `astro add`, `astro check`, etc. This way, we can push for a single interface for all non-essential astro commands, instead of having to teach users `npx/pnpx/ynpx` or maintain a different script for every command. This had tentative buy-in when brought up during a core bug-bash.
- Removes `dev` script in favor of `npm run astro dev` or `npm start`.
- Removes `preview` script in favor of `npm run astro preview`.

## Testing

- N/A

## Docs

- [ ] TODO: Get docs sign-off to update existing usage of `dev` and `preview`
- [ ] TODO: Get docs sign-off to add a note about the `astro` command to docs, probably on the "Installation" page.

2022-07-30 11:36 UTC, delucis requested changes
We need to update the commands table in each of the example’s READMEs as well. They currently look something like this:

<img width="528" alt="Table of available commands from an example README" src="https://user-images.githubusercontent.com/357379/181908983-c895e454-5ffc-4fee-98da-5bdfe67b8562.png">

This is extra important because `"scripts"` in `package.json` are slightly less self-documenting after this change — we need to make sure somewhere else mentions “preview” and “check” so that people know they exist. (In docs we do this in the CLI reference but I’m guessing most people won’t end up there because we make it nice and easy for them with the starter examples — which is great!)

2022-07-30 14:54 UTC, Princesseuh commented
Something I don't like about this change while it makes it easier to run in the CLI, the experience is worse in editors that show NPM scripts and allow you to run them with a click 🙁

2022-08-01 17:38 UTC, FredKSchott commented
Based on feedback here + chatting with @natemoo-re: Keep `dev` script for now. Stackblitz defaults to it, and it might confuse users to see our docs change so close to a release. Unnecessary churn.

2022-08-06 04:29 UTC, FredKSchott commented
Based on more feedback: Lets avoid removing anything right now, and just focus on adding the new `astro` script. We can remove `preview` or go the other direction and add `check` post v1.0.

2022-08-06 04:36 UTC, merged