[chore] replaces hard-coded `minify` values with `vite.build.minify`
withastro/astro pull request #4803
Opened 2022-09-19 14:47 UTC by Enteleform

## Changes

- replaces hard-coded `minify` values with `vite.build.minify`, so that users can override minification from `astro.config`.

2022-09-19 15:29 UTC, matthewp approved these changes
Thanks!

2022-09-19 15:30 UTC, matthewp requested changes
Explained in comment.

2022-09-19 15:31 UTC, matthewp commented
For server JS we are currently leaving that unminified main for easier debugging and because minification is not as necessary for server code. We might change that in the future but I don't think this PR is the right place for that.

So Instead I think using the option in the clientBuild is correct, but you might also need to check the option within the build-css vite plugin. So that it's used for CSS that's built as part of the server JS code.

2022-09-19 15:51 UTC, Enteleform commented
> So Instead I think using the option in the clientBuild is correct

Oh whoops, that's actually what I meant to do & mentioned in the initial comments @ Discord 😅.

&nbsp;  
> check the option within the build-css vite plugin. So that it's used for CSS that's built as part of the server JS code.

Should we just handle this for the client in this PR, and leave the server for another PR if it comes up?

Since you mentioned updating this @ `ssrBuild` would be more complex, I'm wondering if:
```js
{clientJS:config, clientCSS:config, serverJS:static, serverCSS:static}
```
might be make more sense in the meantime than
```js
{clientJS:config, clientCSS:config, serverJS:static, serverCSS:config}

```

2022-09-19 15:55 UTC, matthewp commented
@Enteleform no, for CSS we can honor the `minify` option for both client and server. Since that's going to the client it should not be minified if you set it to false. The server JS is the only thing we want to always remain unminified.

2022-09-19 16:39 UTC, Enteleform commented
> check the option within the build-css vite plugin

Just looked into it and I'm not completely sure what you're asking.

So there's [astro:rollup-plugin-build-css-minify](https://github.com/enteleform-forks/astro/blob/chore/use-vite-minify-config/packages/astro/src/core/build/vite-plugin-css.ts#L242), which I've already updated. Then in same file there's [astro:rollup-plugin-build-css](https://github.com/enteleform-forks/astro/blob/chore/use-vite-minify-config/packages/astro/src/core/build/vite-plugin-css.ts#L80), but it seems like there's presently no minification being applied.

Those are the only two references I've found to `build-css` in the codebase.

Are you saying that minification should be added @ `rollup-plugin-build-css`?

&nbsp;  
-----
&nbsp;  

I did find another point of minification @ [integrations/cloudflare](https://github.com/enteleform-forks/astro/blob/chore/use-vite-minify-config/packages/integrations/cloudflare/src/index.ts#L86).

Should I update that as well?

2022-09-19 21:06 UTC, matthewp approved these changes

2022-09-19 21:06 UTC, matthewp commented
Cloudflare is minifying the server JS so no need to update there. This looks good now! Maybe I just misunderstood before.

2022-09-20 09:16 UTC, bluwy requested changes

2022-09-20 09:16 UTC, bluwy commented on packages/astro/src/core/build/static-build.ts
> +			minify,
I think we could simply remove this line as minify with esbuild is Vite's default. And user config would be derived from `...viteConfig.build` above.

2022-09-20 09:16 UTC, bluwy commented on packages/astro/src/core/build/vite-plugin-css.ts
> +								const minify = settings.config.vite.build?.minify === false ? false : true;
Tiny nit but I think this could be done shorter 😬 
```suggestion
								const minify = settings.config.vite.build?.minify !== false
```

2022-09-20 10:22 UTC, bluwy approved these changes

2022-09-20 12:32 UTC, merged