fix object styles not escaped
withastro/astro pull request #4887
Opened 2022-09-27 13:59 UTC by Calvin-LL

## Changes

Before this PR:

```
<div
  style={{
    backgroundImage: `url("test.png")`,
  }}
>
</div>
```

would be rendered as

```
<div
  style="background-image: url("test.png")"
>
</div>
```

which is invalid HTML, since the quotes in url are not escaped.

After the fix in this PR, the output is:

```
<div
  style="background-image: url(&#34;test.png&#34;)"
>
</div>
```

Also found a bug where `shouldEscape` isn't passed down to `toAttributeString` and I fixed it.

## Testing

Added `astro-object-style` test

## Docs

Minor fix

2022-09-27 14:24 UTC, matthewp requested changes
Looks great, would you mind adding a test? See `packages/astro/test/fixture` for examples of what our tests look like.

Also a changeset is needed:

```
pnpm changeset
```

2022-09-27 22:04 UTC, Calvin-LL commented
> Looks great, would you mind adding a test? See `packages/astro/test/fixture` for examples of what our tests look like.
> 
> Also a changeset is needed:
> 
> ```
> pnpm changeset
> ```

Thanks! I've added tests and ran `changeset`.

2022-09-29 12:14 UTC, matthewp commented
@Calvin-LL this is just a flakey test. Will rerun and it will likely pass. Thank you!

2022-10-04 16:56 UTC, matthewp approved these changes

2022-10-04 16:56 UTC, merged