Add support for `--base` CLI argument
withastro/astro pull request #4917
Opened 2022-09-29 15:46 UTC by natemoo-re

## Changes

- Astro currently allows `--site` and `--root` and a few other CLI arguments.
- This PR adds support for `--base` as well
- Why? Sometimes CLI arguments are very handy, like if you're building an official GitHub Action ([`withastro/action`](https://github.com/withastro/action)) and want to automatically pass in the `--site` and `--base` that GitHub already knows.

## Testing

Tested manually because we don't have equivalent tests for `--site` or other arguments

## Docs

/cc @withastro/maintainers-docs Do we document CLI arguments? No worries if not, it's definitely intended for more advanced use cases.

2022-09-29 16:47 UTC, tony-sull approved these changes
Nice!  Might be worth adding a CLI log that could be checked by a test as well *if* the CLI tests are in a decent spot for it, but not 100% necessary 👍

2022-09-29 18:08 UTC, sarah11918 commented
Removing the docs-maintainers review, as the changes to `@types/astro.ts` won't affect docs!

2022-09-29 18:25 UTC, jasikpark commented
can you update astro help for these?
```
❯ npx astro build --help

   astro  v1.4.0 Build faster websites.

  astro [command] [...flags]

   Commands 
              add  Add an integration.
            build  Build your project and write it to disk.
            check  Check your project for errors.
              dev  Start the development server.
             docs  Open documentation in your web browser.
          preview  Preview your build locally.
        telemetry  Configure telemetry settings.

   Global Flags 
  --config <path>  Specify your config file.
    --root <path>  Specify your project root folder.
        --verbose  Enable verbose logging.
         --silent  Disable all logging.
        --version  Show the version number and exit.
           --help  Show this help message.


```

interesting that `astro build -h` doesn't print help & just builds

2022-09-30 02:59 UTC, natemoo-re commented
Thanks @jasikpark! Updated the `help` command output. Would you mind opening a new issue for tracking `astro build --help`?

2022-09-30 16:00 UTC, jasikpark commented
does this classify as a bug report? since that's the only type of issue in "new issue" that creates an actual issue?

2022-09-30 16:53 UTC, jasikpark commented
> Thanks @jasikpark! Updated the `help` command output. Would you mind opening a new issue for tracking `astro build --help`?

https://github.com/withastro/astro/issues/4935

2022-10-04 16:10 UTC, matthewp commented on .changeset/wise-swans-live.md
> +'astro': patch
Seems like this should be a `minor`

2022-10-04 16:14 UTC, matthewp requested changes
Think this is a minor change.

2022-10-04 16:28 UTC, matthewp approved these changes
lgtm for next minor

2022-10-07 13:40 UTC, matthewp commented
@natemoo-re can you fill out the changeset a bit more? Something like a paragraph, maybe a code example, so that this could be copy/pasted into a blog post. Thank you!

2022-10-26 15:13 UTC, merged