Allow setting domain when deleting cookies
withastro/astro pull request #5341
Opened 2022-11-09 20:20 UTC by alexpdraper

## Changes

Adds `domain` as a property on the delete cookie options. Without this it wasn’t possible to use `Astro.cookies.delete` to delete a cookie that has the domain set.

## Testing

Added a unit test that checks the domain is added to the set-cookie header when provided, similar to the test for the path option.

## Docs

/cc @withastro/maintainers-docs for feedback!
The API reference for `Astro.cookies.delete` doesn’t include the options as one of the arguments.

https://github.com/withastro/docs/blob/main/src/pages/en/reference/api-reference.md#astrocookies

2022-11-10 04:18 UTC, matthewp commented on .changeset/small-ravens-cover.md
> +'astro': patch
This should be a `minor` since it's a new feature.

2022-11-10 04:19 UTC, matthewp commented
The addition makes sense to me. We will indeed need docs before merging this. The docs for that are here: https://github.com/withastro/docs/blob/da3725bf4e3a24647ee240a3816cc5d72e31d9e6/src/pages/en/reference/api-reference.md#astrocookies

2022-11-10 05:06 UTC, matthewp commented
Pretty sure the tests failing is unrelated to your change and it's a problem in `main`. I'm looking to fix that, so please disregard.

2022-11-10 06:28 UTC, matthewp requested changes
- Should be a `minor` change.
- Needs docs

2022-11-10 22:15 UTC, matthewp commented
Thanks @alexpdraper, when you have a docs PR please link to that from here. Then the docs team will review it and approve this PR.

2022-11-11 11:26 UTC, sarah11918 commented
This looks like a useful feature @alexpdraper! You're on our radar now at docs, and we'll be on the lookout for a PR.

Please PR a suggested update to this section of the docs: https://docs.astro.build/en/reference/api-reference/#astrocookies (file is at: https://github.com/withastro/docs/blob/main/src/pages/en/reference/api-reference.md )

and we will help over there with final wording, formatting, and just generally squishing it in to that table!

2022-12-08 13:42 UTC, matthewp commented
Oops, closed by mistake.

2022-12-08 18:24 UTC, alexpdraper commented
> @alexpdraper Are you planning on making the docs changes?

Yes, certainly. Sorry about the delay.

@sarah11918 here’s the docs PR https://github.com/withastro/docs/pull/2151

2022-12-09 15:19 UTC, sarah11918 commented
Docs PR received! Removing Astro-Docs maintainers requirement for review here, and Docs will take this up over there. 🚀

2022-12-12 21:25 UTC, matthewp requested changes
Looks good, this will go out with the next minor (later this week)

2022-12-12 21:33 UTC, alexpdraper commented
Great! Thanks so much!

2022-12-14 15:27 UTC, merged