Change frontmatter injection ordering
withastro/astro pull request #5687
Opened 2022-12-28 15:45 UTC by bholmesdev

## Changes

- Give remark and rehype plugins access to user frontmatter via `data.astro.frontmatter`
- Treat `data.astro.frontmatter` as the source of truth for frontmatter

## Testing

- Update frontmatter injection tests to consider frontmatter mutation

## Docs

TODO

2022-12-28 16:02 UTC, bholmesdev commented on packages/astro/src/vite-plugin-utils/index.ts
> -function isValidAstroData(obj: unknown): obj is MarkdownAstroData {
Move frontmatter injection utils to `@astrojs/markdown-remark`

2022-12-28 17:18 UTC, matthewp requested changes
Blocking as we are not ready to merge `major` changes into main just yet.

2022-12-28 19:27 UTC, matthewp commented
Code looks good! Let's talk about this with the core team before merging next week.

2023-01-02 16:01 UTC, aFuzzyBear reviewed
It was interesting to see how you readjusted the order of the frontmatter process.
So its now safe to say that frontmatter is mutable via the remark tree and the output of that is what is then provided into other contexts

2023-01-03 20:33 UTC, matthewp approved these changes
Approved by TSC, @bholmesdev just need to fix the conflicts.

2023-01-03 21:31 UTC, merged

2023-01-24 23:43 UTC, andersk commented on packages/astro/src/content/vite-plugin-content-assets.ts
> +					export { Content, getHeadings } from ${JSON.stringify(basePath)};
It seems `frontmatter` needed to be added here where `_internal` was removed.

- #5927