@astrojs/loaders
withastro/astro pull request #6331
Opened 2023-02-22 16:41 UTC by matthewp

## Changes

- Implements the loaders proposal: https://github.com/withastro/roadmap/discussions/454

## Testing

- This package is completely separate from core Astro. It could even be used independently. So there are tests in the package only.

## Docs

- Needs docs.

2023-02-22 17:37 UTC, matthewp commented
!preview loaders

2023-02-22 21:49 UTC, matthewp commented
!preview loaders

2023-02-22 22:10 UTC, Princesseuh requested changes
Needs changes 😡

2023-02-23 16:20 UTC, ematipico commented on packages/loaders/src/core.ts
> +	load(...args: any[]): Promise<any>;
How does the compiler behave if we use `unknown` instead of `any`?

2023-02-23 16:20 UTC, ematipico commented on packages/loaders/src/layers/dev.ts
> +export class ForeverInBuildCache<K extends string | null = string | null> implements Layer<K> {
I have never seen this `null = string`. What does it do?

2023-02-23 16:20 UTC, ematipico commented on packages/loaders/src/layers/ratelimit.ts
> +	#counter = 0;
nit: `hitsToCache`

2023-02-23 16:20 UTC, ematipico commented on packages/loaders/src/layers/ratelimit.ts
> +	#outsidePeriod(now: Date): boolean {
nit: `isOutsidePeriod`

2023-02-23 16:20 UTC, ematipico commented on packages/loaders/src/layers/ratelimit.ts
> +	#exceedsLimit(now: Date): boolean {
nit: `hasExceededLimit`

2023-02-23 16:20 UTC, ematipico commented on packages/loaders/test/fetch.test.js
> +import { fetch } from '../dist/index.js';
I am a bit conflicted here... calling `fetch` like the global could confuse unless the users check the top of the file to discover that it's imported. Is it the standard of the community?

2023-03-07 18:32 UTC, matthewp commented
Closing as this was a (successful!) experimentation. We are discussing our next features soon and might revisit this as part of that.

2023-03-07 18:32 UTC, closed without merging