Add a warning when using `encoding` in SSR and `headers` on objects in endpoints
withastro/astro pull request #6358
Opened 2023-02-24 16:04 UTC by Princesseuh

## Changes

Title is a mouthful. Basically, `encoding` is only used to write the files when doing static generation, as such in SSR it doesn't do anything, but people expect it to affect the charset, but since https://github.com/withastro/astro/pull/3841 we always default to `charset=utf-8`. In the future, it would be much better if we only returned responses...

The warning for headers is because returning an object with a certain type of body trips up TypeScript into thinking you're returning a Response since they're "compatible", so a small warning will help nudge users in the right direction.

Close https://github.com/withastro/astro/pull/3841

## Testing

N/A. Tested the warning manually

## Docs

N/A

2023-02-24 16:17 UTC, ematipico approved these changes
Just a nitpick suggestion

2023-02-24 19:31 UTC, matthewp approved these changes

2023-02-27 15:16 UTC, natemoo-re requested changes
Should account for `prerender` as well

2023-02-27 15:44 UTC, natemoo-re requested changes
The check should apply to both `headers` and `encoding` I think?

2023-02-27 15:44 UTC, natemoo-re commented on packages/astro/src/core/endpoint/index.ts
> +	if (env.ssr) {
```suggestion
	if (env.ssr && !mod.prerender) {
```

2023-02-27 15:44 UTC, natemoo-re commented on packages/astro/src/core/endpoint/index.ts
> +		if (response.encoding && !mod.prerender) {
```suggestion
		if (response.encoding) {
```

2023-02-27 15:44 UTC, natemoo-re approved these changes
Looks great!

2023-02-27 18:07 UTC, merged