dont finish the action of the copy before removing all files.
withastro/astro pull request #6472
Opened 2023-03-09 03:34 UTC by wulinsheng123

## Changes

fix: #6431

## Testing

## Docs

2023-03-10 11:07 UTC, ematipico approved these changes

2023-03-13 13:15 UTC, matthewp commented on .changeset/forty-dodos-dress.md
> +'astro': major
this should be a `patch`

2023-03-13 13:15 UTC, matthewp requested changes
Please change the changeset to `patch`

2023-03-15 01:47 UTC, wulinsheng123 commented
> Please change the changeset to `patch`

cc @matthewp

2023-03-15 10:10 UTC, bluwy approved these changes

2023-03-15 17:53 UTC, matthewp approved these changes

2023-03-15 17:53 UTC, merged