File abstraction
withastro/astro pull request #6493
Opened 2023-03-09 21:43 UTC by matthewp

## Changes

- Adds a new abstract, a `File` that is intended to be used any time we are receiving a string that we *think* is a file. It can take files in the form of:
  - File URLs (string and object)
  - Absolute filesystem paths.
  - Root-relative paths
  - Vite's `/@fs` file path prefixed paths.
- And then convert from and to any of the above. 

## Testing

- Testing the class itself in unit tests
- Updated some of the usage that felt safe to swap out, should not break existing tests of course.

## Docs

N/A, internal refactor

2023-03-09 22:49 UTC, natemoo-re reviewed
Seems nice, I'm definitely in favor of this. 

Expect it will take a while to find all the places we're using different abstractions at the moment, but once this propagates through the codebase it'll be great!

2023-03-10 00:50 UTC, Princesseuh commented
Same comment as Nate, this is awesome!

2023-03-10 00:52 UTC, Princesseuh approved these changes

2023-03-10 00:52 UTC, Princesseuh commented on packages/astro/src/core/file/index.ts
> +	 */
In addition to those comments, would it be possible to add a brief explanation as to when you should use each path types? This abstraction makes it easier to use the different ones, but I fear that without explanations, we'll still use the wrong ones at times.

2023-03-10 09:45 UTC, ematipico requested changes

2023-03-10 09:45 UTC, ematipico commented on packages/astro/src/core/file/index.ts
> +			}
This should fall back to `unknown` if we give a `URL` containing actual website URLs.

In fact, passing a website URL will throw an error:
```js
const { fileURLToPath } = require('url');
let url = new URL('https://example.com');
console.log(fileURLToPath(url)); // error
```

2023-03-10 09:45 UTC, ematipico commented on packages/astro/test/units/file/file.test.js
> +		});
We should test against `URL` that are not file paths, e.g. website URLs

2023-03-10 09:47 UTC, ematipico commented
@matthewp The only changes I would request are the tests against non-file paths, the rest is just nitpick/bike sheeding

2023-04-10 17:55 UTC, matthewp commented
Closing as this is a little bit stale. I do want to get back to trying this out again in the future.

2023-04-10 17:55 UTC, closed without merging