Update react links
withastro/astro pull request #6756
Opened 2023-04-05 10:51 UTC by sasoria

## Changes

- Updates React links to the new react documentation site (minor content fix). 
- Part of https://github.com/withastro/docs/issues/2988

## Testing

This has been tested with `pnpm run test`, but no additional tests have been added as this is a minor content fix.

## Docs
No documentation needed.

2023-04-05 15:16 UTC, sarah11918 commented
> There's one last link here: [examples/framework-react/README.md](https://github.com/sasoria/astro/blob/01bd16925d8a9151e2ed5ab6da0ee892dd938ec1/examples/framework-react/README.md?plain=1#L11)

@TheOtterlord, can you make a separate PR for that? Then we can merge this one and not wait for someone to add a new file to this PR!  :raised_hands:

2023-04-05 15:19 UTC, sarah11918 approved these changes
Approving the link updates to the new react docs! Thanks @sasoria! :rocket:

Will want someone else to approve this PR because of the changes to the `.ts` files, which update some logic around links in error messages. Maybe @Princesseuh can confirm these?

2023-04-05 16:40 UTC, Yan-Thomas approved these changes
Nice work @sasoria, LGTM! 

Pointing out that we might need an changeset for this for changing both integration and astro core code?

2023-04-05 18:22 UTC, sasoria commented
Thanks for the feedback! I've added a changeset.

2023-04-06 02:59 UTC, bluwy requested changes

2023-04-06 02:59 UTC, bluwy commented on packages/astro/src/runtime/server/jsx.ts
> +			msg.includes('https://react.dev/warnings/invalid-hook-call-warning');
I don't think React has updated their error message links yet, so we should probably revert this: https://github.com/search?q=repo%3Afacebook%2Freact%20invalid-hook-call&type=code

2023-04-06 02:59 UTC, bluwy commented on packages/integrations/preact/src/server.ts
> +			msg.includes('https://react.dev/warnings/invalid-hook-call-warning');
Here too

2023-04-06 09:42 UTC, sasoria commented
Good catch, I have reverted the changes.

2023-04-06 14:41 UTC, bluwy approved these changes
Thanks!

2023-04-06 14:42 UTC, merged