Implement scopedStyleStrategy
withastro/astro pull request #6771
Opened 2023-04-06 13:04 UTC by matthewp

## Changes

- Adds `scopedStyleStrategy` option to the config.
- Uses this option to pass into the compiler.

## Testing

- Tests that `'where'` is the current default and works as expected.
- Tests that `'class'` omits the where pseudo-selector.

## Docs

- Included in the Astro config.

2023-04-06 13:21 UTC, ematipico requested changes
Blocking because it's a minor

2023-04-06 13:52 UTC, matthewp commented
!preview scopedStyleStrategy

2023-05-02 06:47 UTC, bluwy approved these changes
Changes looks good to me 👍

2023-05-03 08:41 UTC, ematipico approved these changes
Looks good to me!

2023-05-03 08:41 UTC, ematipico commented on .changeset/green-cups-hammer.md
> +To enable class-based scoping you can set it in your config:
```suggestion
Implements a new class-based scoping strategy

This implements the [Scoping RFC](https://github.com/withastro/roadmap/pull/543), providing a way to opt-in to increased style specificity for Astro component styles.

This prevents bugs where global styles override Astro component styles due to CSS ordering and the use of element selectors.

To enable class-based scoping, you can set it in your config:
```

2023-05-03 08:41 UTC, ematipico commented on .changeset/green-cups-hammer.md
> +Note that the 0-specifity `:where` pseudo-selector is still used as the default strategy. The intent is to change `'class'` to be the default in 3.0.
```suggestion
Note that the 0-specificity `:where` pseudo-selector is still the default strategy. The intent is to change `'class'` to be the default in 3.0.
```

2023-05-03 14:10 UTC, sarah11918 reviewed
Looks good, @matthewp! I left some suggestions to consider below.

2023-05-03 14:10 UTC, sarah11918 commented on packages/astro/src/@types/astro.ts
> +	 * Using `'where'` gives you more control over specifity, but requires that you use higher-specifity selectors, layers, and other tools to control which selectors are applied.
```suggestion
	 * Using `'class'` is helpful when you want to ensure that element selectors within an Astro component override global style defaults (e.g. from a global stylesheet).
	 * Using `'where'` gives you more control over specifity, but requires that you use higher-specifity selectors, layers, and other tools to control which selectors are applied.
```
Would this be accurate? Edit as necessary. I think focusing on the need (i.e. that your style tags in components override global defaults) is both helpful to the reader, and can be expressed in a shorter sentence.

2023-05-03 14:10 UTC, sarah11918 commented on packages/astro/src/@types/astro.ts
> +	 *
```suggestion
	 * @version 2.3.5
	 *
```
This might be a good candidate for the "Added In" field?

2023-05-03 15:16 UTC, merged