Pass `compressHTML` settings to manifest
withastro/astro pull request #7488
Opened 2023-06-26 21:35 UTC by natemoo-re

## Changes

- Resolves #7333
- `compressHTML` setting was not passed through to adapters because we weren't saving it in the manifest
- Now the manifest contains `compressHTML` and the base `App` will pass this setting through to `renderPage`

## Testing

Tested manually, but will add a test

## Docs

N/A, bug fix only

2023-06-27 01:43 UTC, matthewp approved these changes

2023-06-27 06:46 UTC, ematipico requested changes
Isn't this, technically, a minor? We're adding a new property to the manifest, which is passed down to the integrations.

I think we should add a test, blocking before merging.

2023-06-27 07:21 UTC, bluwy commented
I think I can see if more as a bug fix as we expect HTML compression to work everywhere, but it didn't handle the manifest part. The new property is an implementation detail of the bug fix. It would be nice to have a test though.

2023-06-28 06:07 UTC, ematipico approved these changes

2023-06-28 19:49 UTC, merged