add site url to the redirect
withastro/astro pull request #8591
Opened 2023-09-18 10:32 UTC by rishi-raj-jain

fix #8499

2023-09-20 08:29 UTC, ematipico reviewed
can we add a test please?

2023-09-20 17:43 UTC, rishi-raj-jain commented
@ematipico Can you guide me on writing tests?

2023-09-22 08:10 UTC, ematipico requested changes
For a test, you could create a new test case inside `static-build.test.js`, and use the fixture `./fixtures/static-build/`.

Then it's just a matter of creating a new page to recreate the issue, and assert that the canonical attribute contains the expected string.

2023-09-22 08:10 UTC, ematipico commented on packages/astro/src/core/build/generate.ts
> +	pipeline: BuildPipeline,
The `pipeline` has already the information you need, you don't need to pass `siteURL` all around.

Just call `pipeline.getConfig()`

2023-09-23 10:16 UTC, rishi-raj-jain commented
> For a test, you could create a new test case inside static-build.test.js, and use the fixture ./fixtures/static-build/.

Then it's just a matter of creating a new page to recreate the issue, and assert that the canonical attribute contains the expected string.

Thanks! That helped, pushed!

2023-09-23 10:36 UTC, ematipico approved these changes

2023-09-25 07:54 UTC, merged