[@astrojs/lit] lit 3.0 compatibility
withastro/astro pull request #8822
Opened 2023-10-13 13:14 UTC by Geoffrey-Pliez

## Changes
upgrade to lit 3.0

## Testing

## Docs

2023-10-13 14:35 UTC, Geoffrey-Pliez commented on packages/integrations/lit/package.json
> +    "sass": "^1.69.3"
it's done ;)

2023-10-13 17:05 UTC, lilnasy requested changes
This is a much requested feature! Thank you for working on this.

I'm going to block this until we merge and release a version of `@astrojs/lit` that continues to work with `lit@^2`.
- https://github.com/withastro/astro/pull/8826
- https://github.com/withastro/astro/pull/8820

Users could then upgrade their projects from lit 2.0 to 3.0 at their own pace.

2023-11-10 13:15 UTC, matthewp commented
@lilnasy if no one is working on fix for the old version then I think we should just go ahead and release this.

2023-11-10 13:25 UTC, lilnasy commented
The fix landed and was released as the linked PRs show, and I dismissed my review when it did. I am not blocking this.

2023-12-12 19:35 UTC, merged