fix: added onError functionality to spinner and used in the current c…
withastro/astro pull request #8993
Opened 2023-11-03 08:33 UTC by skirianov

Added `onError` function to handle errors inside `spinner` if `while` function throws an errors. 

- new `onError` property inside `dependencies.ts` spinner
- `while` function catches and throws an error if installing dependencies fails
- `messages.ts/spinner` accept new args

## Changes

- What does this change?
- Be short and concise. Bullet points can help!
- Before/after screenshots can help as well.
- Don't forget a changeset! `pnpm exec changeset`

## Testing

Manual QA

## Docs

No need to update docs, it's just DX fix

2023-11-06 11:03 UTC, sarah11918 reviewed
Hi @skirianov! Thanks for this fix.. seems... pretty important!  😅 

Just added a tiny suggestion to the changeset for your consideration, since we think of them as being user-facing, like docs. So, in our case, I often go back and look at any actual issue that was reported and use that as the basis for a fix, vs the more technical implication of it. See what you think!

2023-11-06 11:03 UTC, sarah11918 commented on .changeset/silent-experts-sip.md
> +Fixed spinner to handle errors if install dependencies fails
```suggestion
Fixes an issue where a successful "Dependencies installed" message is displayed even when installing dependencies fails.
```
Something like this maybe?

2023-11-06 11:15 UTC, skirianov commented
@sarah11918 haha, yeah, quite an edge case, but still possible :D 

Loved your suggestion, commited. 

Need to first merge https://github.com/withastro/cli-kit/pull/25 and publish package before we can merge this one :)

2023-11-09 09:31 UTC, skirianov commented
Hi @sarah11918, updated the `package.json` and `pnpm-lock` to align with `cli-kit: 0.3.1` and resolved merge conflicts. 

If you're fine with it, we can merge the PR. Thanks :)

2023-11-09 15:26 UTC, ematipico requested changes
I think some merge/rebase went wrong, because now this PR has changes that don't to this PR. Could you please fix them? I expect to have two/three files changed (changeset and files related to `create-astro`)

2023-11-09 15:26 UTC, ematipico commented on .changeset/silent-experts-sip.md
> +'create-astro': major
Why is this a `major`? I think it should be a `patch` because **if fixes** a bug. Do you agree?

2023-11-09 15:26 UTC, ematipico commented on packages/astro/components/Image.astro
> +const additionalAttributes: Record<string, any> = {};
This change isn't part of the PR. Can you revert it, please?

2023-11-09 15:26 UTC, ematipico commented on packages/astro/components/Picture.astro
We should revert these changes

2023-11-10 10:01 UTC, closed without merging

2023-11-10 10:06 UTC, skirianov commented
@ematipico dang it, I reset the commit history and force pushed it....I'll update the PR