Descriptive image error
withastro/astro pull request #9352
Opened 2023-12-06 21:21 UTC by tmcw

## Changes

Right now, if you have an image in your site that is too big, you get a message saying that an image was too big, but not which one. This PR improves the error so that it tells you which one.

## Testing

I really don't know how to test this, tbh - I'd probably use `npm link` but I don't know how that'd work with pnpm.

## Docs

This doesn't need docs: it's just an improved error.

2023-12-07 02:47 UTC, jacobthesheep commented
I believe pnpm link is a thing

2023-12-18 18:46 UTC, florian-lefebvre requested changes

2023-12-18 18:46 UTC, florian-lefebvre commented on .changeset/famous-cars-sell.md
> +'astro': minor
```suggestion
'astro': patch
```

2023-12-19 09:37 UTC, ematipico commented
@tmcw how did you test your changes? I mean, how did you make sure you could see the new errors?

Regardless, here's a suggestion: run `pnpm build` inside the astro package , create a new astro project on your machine, inside your new astro project run `pnpm link ../astro/packages/astro` (fix the path, but you want to link the built and local version of your astro), then run your project in dev mode and try to recreate the errors.

Take screenshots to show us the results.

2023-12-19 15:07 UTC, ematipico approved these changes

2023-12-19 15:36 UTC, sarah11918 approved these changes
Just tiny adjustments! Great error message!

2023-12-19 15:36 UTC, sarah11918 commented on packages/astro/src/core/errors/errors-data.ts
> + * Astro could not transform one of your image. Oftentimes, this is caused by a corrupted or malformed image and re-exporting the image from your image editor may fix this issue.
```suggestion
 * Astro could not transform one of your images. Often, this is caused by a corrupted or malformed image. Re-exporting the image from your image editor may fix this issue.
```

2023-12-19 16:14 UTC, merged