Opt-out ViewTransition for cross-origin form.
withastro/astro pull request #9693
Opened 2024-01-14 11:39 UTC by kidylee

For issue #9676

2024-01-14 11:58 UTC, florian-lefebvre commented on .changeset/poor-cherries-buy.md
> +Opt-out ViewTransition for cross-origin form
```suggestion
Disables View Transition form handling when the `action` property points to an external URL
```

2024-01-14 12:02 UTC, kidylee commented on .changeset/poor-cherries-buy.md
> +Opt-out ViewTransition for cross-origin form
Thanks @florian-lefebvre.

2024-01-14 23:57 UTC, martrapp requested changes
Hello @kidylee! Thank you for your PR!

While your change is very clean, robust and understandable, I would like to ask you for a more compact implementation. We are a bit concerned about the code size of the ViewTransition.astro and would like to keep it rather small.

2024-01-14 23:57 UTC, martrapp commented on packages/astro/components/ViewTransitions.astro
> +	function isCrossOrigin(action?: string): boolean {
We try to keep the file size of ViewTransition.astro small. Could you please inline that call?

2024-01-14 23:57 UTC, martrapp commented on packages/astro/components/ViewTransitions.astro
> +		if (!action) {
if inlined, action is always truthy. This if isn't necessary then.

2024-01-14 23:57 UTC, martrapp commented on packages/astro/components/ViewTransitions.astro
> +		return actionURL.hostname !== location.hostname;
cross origin is more than the host. It should also include protocol and port.
Better use actionURL.origin !== location.origin?

2024-01-14 23:57 UTC, martrapp commented on packages/astro/components/ViewTransitions.astro
> +			if (isCrossOrigin(action)) {
```suggestion
			if (new URL(action, location.href).origin !== location.origin) {
```

2024-01-14 23:57 UTC, martrapp commented on packages/astro/e2e/view-transitions.test.js
> +		const loads = [];
```suggestion
```

2024-01-14 23:57 UTC, martrapp commented on .changeset/poor-cherries-buy.md
> +Disables View Transition form handling when the `action` property points to an external URL
```suggestion
Fixes the submission of forms that have a cross origin `action` property when used with view transitions   
```

2024-01-15 03:47 UTC, kidylee commented
> Hello @kidylee! Thank you for your PR!
> 
> While your change is very clean, robust and understandable, I would like to ask you for a more compact implementation. We are a bit concerned about the code size of the ViewTransition.astro and would like to keep it rather small.

Thanks for your patiently guidance, I have made it inline and follow the same pattern of `link` logic does: composing `return` conditions in a single `if`, hopefully it is a good practice.

` if (method === 'dialog' || location.origin !== new URL(action, location.href).origin) `

2024-01-15 07:28 UTC, merged