Fix HMR in MDX deps in Content Collections
withastro/astro pull request #9956
Opened 2024-02-02 21:34 UTC by matthewp

## Changes

- Hopefully fixes https://github.com/withastro/astro/issues/9794
  - Definitely fixes a test case provided there
- The underlying issue is that the virtual propagated asset modules depend on the underlying MDX modules, but they also depend on their underlying assets which we get with getStylesForURL, etc. But these things are not "reactive" to changes in the module.
- This is all caused because Vite has "soft invalidation" of dependencies, the propagated asset module is not invalidated when parents change. This is correct and expected.
- The fix is to make grabbing the assets a function call, rather than a static thing that's compiled into the module definitions. This means every time `entry.render()` is called in dev, it gets fresh set of styles/scripts, so it should always be right.

## Testing

- Added a new E2E test

## Docs

N/A, bug fix

2024-02-02 22:15 UTC, matthewp commented
!preview cc-hmr

2024-02-02 23:31 UTC, HiDeoo commented
Just tested on the few Starlight related scenarios I had in my notes having that issue, and just like Hippo, it now works perfectly with the preview release :thumbsup:

2024-02-03 08:40 UTC, florian-lefebvre commented on .changeset/soft-bags-flash.md
> +Fix HMR in MDX deps in Content Collections
```suggestion
Fixes HMR for MDX dependencies in Content Collections
```

2024-02-04 01:09 UTC, natemoo-re approved these changes
It’s wild that this works, but I’m really glad it does! Nice one.

2024-02-04 01:09 UTC, natemoo-re commented on packages/astro/src/content/vite-plugin-content-assets.ts
> +function getPropagatedAssets() {
Dang. Clever solution! Not _too_ clever of course, just the right amount of clever. 👌

2024-02-04 04:08 UTC, Princesseuh approved these changes
Just two small comments, thank you very much for taking this one! Gonna be a big productivity boost, especially for Starlight users.

2024-02-04 04:08 UTC, Princesseuh commented on packages/astro/src/virtual-modules/dev-helpers.ts
> +// TODO
Was there something to be done here?

2024-02-04 04:08 UTC, Princesseuh commented on packages/astro/test/units/test-utils.js
> +			throw new Error('This module can\'t be loaded threw here. blah');
Not sure how likely that error is, but if it's real, a good error message would be better so we don't eventually have to explain to a new contributor why that error happens, ha

2024-02-05 07:29 UTC, bluwy requested changes
It seems like this could break markdoc? https://github.com/withastro/astro/blob/6d273bed13e1ba6e69f8e0c2228ce461dceed148/packages/integrations/markdoc/components/TreeNode.ts#L126-L128

I'm not very comfortable with the `.ssrModule` assignment because it means crossing an explicitly separate boundary between the "Vite-plugin runtime" and "SSR app runtime". It can also make supporting other envs in the future, like workerd in dev, harder.

<details>
<summary>(Collapsing my comments because it's outdated)</summary>


It looks like the core issue here is that if `/my/component/Foo.astro` is invalidated, we should also invalidate `/my/component/Foo.astro?astroPropagatedAssets` hardly. I can't think of a cleaner fix today, but if we need to workaround it, maybe we should directly fix the invalidation, e.g. patching `server.moduleGraph.invalidateModule`, check if we're invalidating an `.astro` module, then try to invalidate the `.astro?astroPropagatedAssets` module as well?

I think what Vite can fix, which I can try to implement, is that the `/my/component/Foo.astro?astroPropagatedAssets` transform can call `this.addWatchFile('/my/component/Foo.astro')`, which implies that even if we import it in code, whenever the watched file is changed, we should still hard-invalidate it.

</details>

EDIT: I got a better idea of the problem now today. The issue is that when any imported modules recursively down from the propagated module is updated, the propagated module also needs to be invalidated. Because `getStylesForURL` and `getScriptsForURL` crawls all of its imported modules recursively to retrieve that.

The proper way is to register all of its imported modules with `this.addWatchFile`, maybe `get...ForURL` can return that based on the walked `mod.file`. Another workaround is to simply invalidate all propagated modules whenever `handleHotUpdate` is invoked, so that they are re-transformed on the next request. Or another workaround is this PR, so I could see this PR being something worth considering too 🤔  I think I'd still lean on the first way (in this paragraph) though.

2024-02-05 14:18 UTC, bluwy commented
!preview cc-hmr

2024-02-06 13:28 UTC, matthewp commented
lgtm, willing to try this approach.

2024-02-06 14:54 UTC, bluwy approved these changes

2024-02-06 14:56 UTC, merged